# Generated by Django 5.2.17 on 2026-08-30 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repository_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_repo_id', models.BigIntegerField()),
                ('owner', models.TextField()),
                ('name', models.TextField()),
                ('full_name', models.TextField()),
                ('html_url', models.TextField()),
                ('default_branch', models.TextField(blank=True, null=True)),
                ('visibility', models.TextField(choices=[('public', 'Public'), ('private', 'Private')])),
                ('access_level', models.TextField(choices=[('owner', 'Owner'), ('write', 'Write'), ('collaborator', 'Collaborator')])),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'db_table': 'repositories',
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'github_repo_id'), name='repositories_unique_user_github_repo_id'), models.UniqueConstraint(fields=('user', 'owner', 'name'), name='repositories_unique_user_owner_name'), models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='repositories_visibility_valid'), models.CheckConstraint(condition=models.Q(('access_level__in', ['owner', 'write', 'collaborator'])), name='repositories_access_level_valid')],
            },
        ),
    ]
