# Generated by Django 5.2.17 on 2026-09-05 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('scan_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_scan_id', models.UUIDField(blank=True, null=True)),
                ('github_user_id', models.BigIntegerField()),
                ('github_username', models.TextField()),
                ('github_repo_id', models.BigIntegerField()),
                ('repo_full_name', models.TextField()),
                ('ecosystems', models.TextField()),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classification', models.TextField(choices=[('safe', 'Safe'), ('medium', 'Medium'), ('high_alert', 'High alert')])),
                ('dependency_count', models.IntegerField(default=0)),
                ('flagged_dependency_count', models.IntegerField(default=0)),
                ('scoring_formula_version', models.TextField()),
                ('data_source', models.TextField(choices=[('live_scan', 'Live scan'), ('backfill', 'Backfill')], default='live_scan')),
                ('snapshot_date', models.DateField(blank=True, null=True)),
                ('sampling_weight', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('scanned_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'scan_history',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['github_repo_id', 'snapshot_date'], name='scan_history_repo_date_idx'), models.Index(fields=['data_source'], name='scan_history_source_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('risk_score__gte', 0), ('risk_score__lte', 100)), name='scan_history_risk_score_range'), models.CheckConstraint(condition=models.Q(('classification__in', ['safe', 'medium', 'high_alert'])), name='scan_history_classification_valid'), models.CheckConstraint(condition=models.Q(('data_source__in', ['live_scan', 'backfill'])), name='scan_history_data_source_valid'), models.CheckConstraint(condition=models.Q(('dependency_count__gte', 0), ('flagged_dependency_count__gte', 0)), name='scan_history_counts_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='DependencyHistory',
            fields=[
                ('dependency_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ecosystem', models.TextField(choices=[('npm', 'npm'), ('pypi', 'PyPI')])),
                ('package_name', models.TextField()),
                ('manifest_path', models.TextField()),
                ('dependency_group', models.TextField(choices=[('runtime', 'Runtime'), ('development', 'Development'), ('optional', 'Optional'), ('peer', 'Peer'), ('build', 'Build'), ('unknown', 'Unknown')])),
                ('declared_specifier', models.TextField(blank=True, null=True)),
                ('resolved_version', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, choices=[('lockfile', 'From lockfile'), ('pinned', 'Pinned in manifest'), ('range_latest_approx', 'Approximated against latest')], null=True)),
                ('latest_version', models.TextField(blank=True, null=True)),
                ('staleness_days', models.IntegerField(blank=True, null=True)),
                ('versions_behind_major', models.IntegerField(default=0)),
                ('versions_behind_minor', models.IntegerField(default=0)),
                ('versions_behind_patch', models.IntegerField(default=0)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('deprecation_reason', models.TextField(blank=True, null=True)),
                ('vulnerability_count', models.IntegerField(default=0)),
                ('highest_severity', models.TextField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], null=True)),
                ('cvss_max', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_unassessable', models.BooleanField(default=False)),
                ('risk_component_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dependencies', to='research.scanhistory')),
            ],
            options={
                'db_table': 'dependency_history',
                'ordering': ['manifest_path', 'package_name'],
                'indexes': [models.Index(fields=['scan_history'], name='dep_history_scan_idx'), models.Index(fields=['package_name', 'ecosystem'], name='dep_history_package_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ecosystem__in', ['npm', 'pypi'])), name='dep_history_ecosystem_valid'), models.CheckConstraint(condition=models.Q(('vulnerability_count__gte', 0)), name='dep_history_vuln_count_non_negative'), models.CheckConstraint(condition=models.Q(('risk_component_score__isnull', True), models.Q(('risk_component_score__gte', 0), ('risk_component_score__lte', 100)), _connector='OR'), name='dep_history_component_score_range')],
            },
        ),
    ]
