# Generated by Django 5.2.17 on 2026-09-11 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecutionTrace',
            fields=[
                ('trace_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_report_id', models.UUIDField(blank=True, null=True)),
                ('source_scan_id', models.UUIDField(blank=True, null=True)),
                ('github_user_id', models.BigIntegerField()),
                ('repo_full_name', models.TextField()),
                ('ecosystem', models.TextField(choices=[('npm', 'npm'), ('pypi', 'PyPI')])),
                ('package_name', models.TextField()),
                ('resolved_version', models.TextField(blank=True, null=True)),
                ('branch_taken', models.TextField(choices=[('reason_available', 'Reason available'), ('no_reason', 'No reason')])),
                ('retrieval_query', models.TextField(blank=True, null=True)),
                ('retrieved_chunks_json', models.JSONField(default=list)),
                ('generation_json', models.JSONField(default=dict)),
                ('grounding_confidence', models.TextField(choices=[('sufficient', 'Sufficient'), ('low', 'Low')])),
                ('model_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_execution_traces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['package_name', 'ecosystem'], name='agent_trace_package_idx'), models.Index(fields=['branch_taken'], name='agent_trace_branch_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ecosystem__in', ['npm', 'pypi'])), name='agent_trace_ecosystem_valid'), models.CheckConstraint(condition=models.Q(('branch_taken__in', ['reason_available', 'no_reason'])), name='agent_trace_branch_valid'), models.CheckConstraint(condition=models.Q(('grounding_confidence__in', ['sufficient', 'low'])), name='agent_trace_grounding_valid')],
            },
        ),
    ]
