"""`research_data/validation_report/` — study S1's results section, generated.

§10 Phase 12: "`report.py` -> `research_data/validation_report/` (report.md +
correlation scatter, weight-comparison chart, sensitivity table, confusion
matrices as PNG/CSV)." The mentor demo reads it aloud: "This folder is study
S1's results section, generated by one command."

**It opens with WP-6's sign-off checklist, already computed.** File B gives the
teammate six checks to walk in `wp6_signoff.md`; each is a line here with its
number filled in and a verdict beside it, in the same spirit as the corpus
reports (§11.15). A run that fails one fails it on the first page.

**Every caveat sits beside the number it qualifies.** File C §2.4.3: the OSV
reference's circularity sentence goes "adjacent to the number, not buried".
The Scorecard construct caveat, the sampling-weight note and the
cross-sectional limit are placed the same way.

**Figures are optional; the CSVs are not.** The PNGs need matplotlib, which is
research-only and was blocked by an Application Control policy on the
development machine (§11.22). Every figure's data is also a CSV, so a machine
that cannot draw still produces every number, and the report says which
figures were skipped and why.

**The candidate weights file is written here and nowhere else.** It is named
`weights_v2_candidate.yaml`, carries `derivation: ahp-candidate-pending-wp6`,
and is validated by the product's own loader before it is written. It is not
in `backend/weights/` and nothing loads it: adopting it is §10 Phase 12's
seventh commit, after WP-6 signs.
"""

from __future__ import annotations

import csv
import json
import statistics
import textwrap
from dataclasses import dataclass
from pathlib import Path

from apps.scoring.normalize import SIGNAL_NAMES

from . import agree, ahp, anchors, candidates, reference
from .harness import CANDIDATE, ENTROPY, OSV, SCORECARD, ValidationRun

REPORT_FILENAME = "report.md"
INPUTS_FILENAME = "inputs.json"
CANDIDATE_FILENAME = "weights_v2_candidate.yaml"

#: WP-1's quality check, kept for v2 (File B WP-6 item 6: "a weight ≈0 or ≈0.8
#: needs a sentence of justification or a bounce").
MIN_SENSIBLE_WEIGHT = 0.05
MAX_SENSIBLE_WEIGHT = 0.60

OK = "ok"
ATTENTION = "attention"
FAILS = "fails"
NOT_RUN = "not run"


def _f(value: float | None, places: int = 3) -> str:
    return "n/a" if value is None else f"{value:.{places}f}"


def _interval(found: tuple[float, float] | None) -> str:
    return "" if found is None else f"[{found[0]:.3f}, {found[1]:.3f}]"


def _weights_row(weights) -> str:
    return " / ".join(f"{float(weights[signal]):.4f}" for signal in SIGNAL_NAMES)


# ── the WP-6 checklist ─────────────────────────────────────────────────────


@dataclass(frozen=True)
class Check:
    number: int
    title: str
    status: str
    detail: str


def checklist(run: ValidationRun) -> list[Check]:
    """File B WP-6's six sign-off items, each with its number and a verdict."""
    checks: list[Check] = []

    checks.append(
        Check(
            1,
            "Reconciled matrix CR < 0.10",
            OK if run.ahp.passes else FAILS,
            f"CR = {run.ahp.consistency_ratio:.4f} (λ_max {run.ahp.lambda_max:.4f}, "
            f"CI {run.ahp.consistency_index:.4f}, RI {run.ahp.random_index:.2f}).",
        )
    )

    results = run.anchor_results.get(CANDIDATE, [])
    known = [result for result in results if result.row.is_known_anchor]
    if not run.anchor_rows:
        checks.append(
            Check(2, "Every known anchor ≥ Medium", NOT_RUN, "No --anchors given.")
        )
    else:
        verdicts = [result.verdict for result in known]
        failed = [r.row.full_name for r in known if r.verdict == anchors.VERDICT_FAIL]
        invalid = [r.row.full_name for r in known if r.verdict == anchors.VERDICT_INVALID]
        missing = [
            r.row.full_name for r in known if r.verdict == anchors.VERDICT_NOT_SCANNED
        ]
        status = (
            OK if known and all(v == anchors.VERDICT_PASS for v in verdicts) else FAILS
        )
        detail = (
            f"{verdicts.count(anchors.VERDICT_PASS)} of {len(known)} known anchors pass."
        )
        if failed:
            detail += f" **Classified Safe (automatic fail):** {', '.join(failed)}."
        if invalid:
            detail += (
                f" Anchor package not seen at its version, or not flagged — an invalid "
                f"anchor, a WP-2 problem: {', '.join(invalid)}."
            )
        if missing:
            detail += f" Not scanned: {', '.join(missing)}."
        checks.append(Check(2, "Every known anchor ≥ Medium", status, detail))

    candidate_comparisons = [
        c for c in run.comparisons if c.first_name.startswith(CANDIDATE)
    ]
    if candidate_comparisons:
        parts = []
        worst = "strong"
        for comparison in candidate_comparisons:
            parts.append(
                f"{comparison.second_name.split('[')[-1].rstrip(']')}: cosine "
                f"{_f(comparison.cosine)} ({comparison.band}), top two "
                f"{'identical' if comparison.top_two_identical else 'differ'}"
            )
            if comparison.band == "tension" or (
                comparison.band == "partial" and worst == "strong"
            ):
                worst = comparison.band
        status = (
            OK
            if worst == "strong"
            and all(c.top_two_identical for c in candidate_comparisons)
            else ATTENTION
        )
        checks.append(
            Check(
                3,
                "AHP vs entropy: broad agreement, or the disagreement acknowledged",
                status,
                "; ".join(parts)
                + (
                    ". Disagreement is not a failure (File C §2.4.2) but the sign-off "
                    "must discuss it."
                    if status != OK
                    else "."
                ),
            )
        )
    else:
        checks.append(
            Check(3, "AHP vs entropy", NOT_RUN, "No entropy vector could be computed.")
        )

    overall = _agreement(run, CANDIDATE, SCORECARD, "all")
    osv = _agreement(run, CANDIDATE, OSV, "all")
    if overall is None:
        checks.append(
            Check(
                4,
                "Correlation vs deps.dev Scorecard positive and non-trivial",
                NOT_RUN,
                "--skip-reference was given; deps.dev was not asked.",
            )
        )
    else:
        rho = overall.correlation("spearman")
        value = rho.value if rho else None
        positive = value is not None and value > 0.1
        checks.append(
            Check(
                4,
                "Correlation vs deps.dev Scorecard positive and non-trivial",
                OK if positive else ATTENTION,
                f"Spearman rho = {_f(value)} {_interval(rho.interval if rho else None)} over "
                f"{overall.covered} of {overall.repositories} repositories with a "
                f"Scorecard. The OSV roll-up's circularity caveat is printed beside its "
                f"number in RQ2"
                + (
                    f" (OSV rho = {_f(osv.correlation('spearman').value)})."
                    if osv and osv.correlation("spearman")
                    else "."
                ),
            )
        )

    parts = []
    robust = True
    for label in (CANDIDATE, ENTROPY):
        summary = run.summaries.get(label)
        if summary is None:
            continue
        robust = robust and summary.robust
        parts.append(
            f"{label}: max flip rate {summary.max_weight_rate_10:.1%} at ±10%, "
            f"{summary.max_weight_rate_20:.1%} at ±20%"
        )
    checks.append(
        Check(
            5,
            "Sensitivity: flip rate under 15% at ±10-20%, both vectors",
            OK if robust else ATTENTION,
            "; ".join(parts)
            + "."
            + ("" if robust else " Raise with the developer before signing."),
        )
    )

    odd: list[str] = []
    for ecosystem in ("npm", "pypi"):
        vector = run.candidate.weights[ecosystem]
        if sum(vector.values()) != 1:
            odd.append(f"{ecosystem} sums to {sum(vector.values())}")
        for signal in SIGNAL_NAMES:
            weight = float(vector[signal])
            if weight < MIN_SENSIBLE_WEIGHT or weight > MAX_SENSIBLE_WEIGHT:
                odd.append(f"{ecosystem} {signal} = {weight:.4f}")
    checks.append(
        Check(
            6,
            "Final vectors sum to 1 and are non-degenerate",
            OK if not odd else ATTENTION,
            "npm "
            + _weights_row(run.candidate.weights["npm"])
            + "; pypi "
            + _weights_row(run.candidate.weights["pypi"])
            + " (deprecation / severity / count / staleness)."
            + (f" Needs a sentence of justification: {'; '.join(odd)}." if odd else ""),
        )
    )
    return checks


def _agreement(run: ValidationRun, vector: str, reference_name: str, group: str):
    for found in run.agreements:
        if (
            found.vector == vector
            and found.reference == reference_name
            and found.group == group
        ):
            return found
    return None


# ── markdown ───────────────────────────────────────────────────────────────


def _distribution(values: list[float]) -> str:
    if not values:
        return "n=0"
    ordered = sorted(values)
    quartiles = (
        statistics.quantiles(ordered, n=4) if len(ordered) > 1 else [ordered[0]] * 3
    )
    return (
        f"n={len(ordered)}, min {ordered[0]:.2f}, Q1 {quartiles[0]:.2f}, median "
        f"{quartiles[1]:.2f}, Q3 {quartiles[2]:.2f}, max {ordered[-1]:.2f}"
    )


def render_markdown(
    run: ValidationRun, figures: list[Path], skipped_figures: str | None
) -> str:
    panel = run.panel
    lines: list[str] = [
        "# S1 validation report",
        "",
        "Generated by `manage.py validate_formula` (§10 Phase 12) on "
        f"{run.generated_at[:19]}Z. Every score below is **recomputed** from the "
        "stored signals of one corpus snapshot through the shipped engine (D6, "
        "File C §1.1); no stored score is read as a result and no row was written.",
        "",
        "## Inputs",
        "",
        "| | |",
        "|---|---|",
        f"| Corpus snapshot | `{panel.snapshot_date}`: {len(panel.repositories)} repositories, "
        f"{panel.occurrence_count} occurrences |",
        f"| Reconciled AHP matrix | `{run.ahp.matrix.source}` (sha256 `{run.ahp_sha256[:16]}…`) |",
        "| Anchor set | "
        + (
            f"`{run.inputs.anchors_path.name}` (sha256 `{(run.anchor_sha256 or '')[:16]}…`)"
            if run.inputs.anchors_path
            else "not given"
        )
        + " |",
        f"| Baseline weights | `{run.baseline.version}` ({run.baseline.derivation}) |",
        f"| Seed / bootstrap | {run.inputs.seed} / {run.inputs.bootstrap} resamples of repositories |",
        "",
        "**Reproduction check (D6).** "
        + (
            f"All {run.reproduction.checked} stored repository scores reproduce exactly "
            f"when recomputed under the version on their own row."
            if run.reproduction.all_match
            else f"{run.reproduction.matched} of {run.reproduction.checked} stored "
            f"scores reproduce under their own version"
            + (
                f"; versions that could not be loaded: "
                f"{', '.join(run.reproduction.unloadable_versions)}"
                if run.reproduction.unloadable_versions
                else ""
            )
            + ". **Every recomputed number below is suspect until this is explained.**"
        ),
        "",
        "## WP-6 sign-off checklist",
        "",
        "File B WP-6's six items. `wp6_signoff.md` walks each one.",
        "",
        "| # | Check | Status | Detail |",
        "|---|---|---|---|",
    ]
    for check in checklist(run):
        lines.append(
            f"| {check.number} | {check.title} | **{check.status}** | {check.detail} |"
        )

    # ── RQ1 ──
    lines += [
        "",
        "## RQ1 — Do subjective (AHP) and objective (entropy) weights agree?",
        "",
        "### The reconciled AHP matrix",
        "",
        "| | " + " | ".join(run.ahp.matrix.labels) + " |",
        "|---|" + "---|" * run.ahp.matrix.n,
    ]
    for i, label in enumerate(run.ahp.matrix.labels):
        lines.append(
            f"| {label} | "
            + " | ".join(
                ahp.format_value(run.ahp.matrix.values[i][j])
                for j in range(run.ahp.matrix.n)
            )
            + " |"
        )
    lines += [
        "",
        "Principal eigenvector: "
        + ", ".join(
            f"{label} **{weight:.4f}**"
            for label, weight in zip(run.ahp.matrix.labels, run.ahp.weights, strict=True)
        )
        + f". λ_max = {run.ahp.lambda_max:.4f}, CI = {run.ahp.consistency_index:.4f}, "
        f"RI = {run.ahp.random_index:.2f}, **CR = {run.ahp.consistency_ratio:.4f}**.",
        "",
    ]
    for note in run.ahp.matrix.notes:
        lines.append(f"- {note}")
    lines += [
        "",
        f"**PyPI.** {run.pypi_rule}",
        "",
        "### Entropy weights from the corpus",
        "",
        "Over every assessable occurrence of the snapshot, normalised exactly as the "
        "formula normalises it. A missing staleness is left out of that column only "
        "(§5.2). Intervals: 95% repository-cluster bootstrap.",
        "",
        "| Ecosystem | Signal | Rows | Non-zero | Entropy | Weight | 95% interval | Weight (sampling-weighted) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for ecosystem, found in run.entropy.items():
        weighted = run.entropy_weighted[ecosystem].vector()
        for column in found.columns:
            lines.append(
                f"| {ecosystem} | {column.signal} | {column.rows:.0f} | {column.nonzero} | "
                f"{_f(column.entropy, 4)} | {_f(column.weight, 4)} | "
                f"{_interval(found.intervals.get(column.signal))} | "
                f"{_f(weighted.get(column.signal), 4)} |"
            )
    for note in run.entropy_notes:
        lines.append(f"\n{note}")
    lines += [
        "",
        "### Agreement",
        "",
        "| Vectors | Cosine | Band | Spearman (weights) | Order (first) | Order (second) | Largest gap |",
        "|---|---|---|---|---|---|---|",
    ]
    for comparison in run.comparisons:
        signal, gap = comparison.largest_gap
        lines.append(
            f"| {comparison.first_name} vs {comparison.second_name} | {_f(comparison.cosine)} | "
            f"{comparison.band} | {_f(comparison.spearman)} | "
            f"{' > '.join(comparison.first_order)} | {' > '.join(comparison.second_order)} | "
            f"{signal} {gap:+.3f} |"
        )
    lines += [
        "",
        "File C H1: cosine ≥ 0.90 *and* the same top two signals. Entropy weights a "
        "signal by how unevenly it is spread, so a rare-but-decisive signal such as "
        "deprecation can carry more entropy weight than a judge gives it, or less if "
        "the judge weighs its severity: a divergence there is interpretable (File C "
        "§2.4.2), and a cosine below 0.75 leads the discussion.",
    ]

    # ── RQ2 ──
    lines += [
        "",
        "## RQ2 — Do the scores converge with an independent reference?",
        "",
        f"> {reference.SCORECARD_CAVEAT}",
        "",
        f"> {reference.OSV_CAVEAT}",
        "",
        "Repository score (higher is healthier) against each reference, oriented so a "
        "positive correlation is the expected direction. Intervals: 95% percentile "
        "bootstrap over repositories. The weighted column applies `sampling_weight` "
        "(File C §1.3); the unweighted value is the primary one.",
        "",
        "| Formula | Reference | Group | Covered | Spearman rho | 95% interval | Pearson r | 95% interval | rho weighted | r weighted |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for found in run.agreements:
        rho = found.correlation("spearman")
        r = found.correlation("pearson")
        rho_w = found.correlation("spearman", weighted=True)
        r_w = found.correlation("pearson", weighted=True)
        name = _reference_name(found.reference)
        lines.append(
            f"| {found.vector} | {name} | {found.group} | {found.covered}/{found.repositories} | "
            f"{_f(rho.value if rho else None)} | {_interval(rho.interval if rho else None)} | "
            f"{_f(r.value if r else None)} | {_interval(r.interval if r else None)} | "
            f"{_f(rho_w.value if rho_w else None)} | {_f(r_w.value if r_w else None)} |"
        )
    if run.scorecards is not None:
        statuses: dict[str, int] = {}
        for reading in run.scorecards.values():
            statuses[reading.status] = statuses.get(reading.status, 0) + 1
        lines += [
            "",
            "deps.dev coverage: "
            + ", ".join(f"{status} {count}" for status, count in sorted(statuses.items()))
            + ".",
        ]
    lines += [
        "",
        "### Three-class agreement (Cohen's kappa), under three cuts of the reference",
        "",
        "| Formula | Reference | Group | kappa tertiles | kappa matched proportions | kappa equal thirds of 0-10 |",
        "|---|---|---|---|---|---|",
    ]
    for found in run.agreements:
        if not found.confusions:
            continue
        kappas = {c.bucketing: c.kappa for c in found.confusions}
        lines.append(
            f"| {found.vector} | {_reference_name(found.reference)} | {found.group} | "
            f"{_f(kappas.get(agree.TERTILES))} | {_f(kappas.get(agree.MATCHED))} | "
            f"{_f(kappas.get(agree.EQUAL_THIRDS))} |"
        )
    primary = _agreement(run, CANDIDATE, SCORECARD, "all") or _agreement(
        run, CANDIDATE, OSV, "all"
    )
    if primary is not None and primary.confusion(agree.TERTILES) is not None:
        matrix = primary.confusion(agree.TERTILES).matrix
        lines += [
            "",
            f"Confusion, {primary.vector} vs {_reference_name(primary.reference)} "
            "(tertiles), rows = "
            "formula class, columns = reference bucket:",
            "",
            "| | " + " | ".join(agree.CLASSES) + " |",
            "|---|---|---|---|",
        ]
        for name, row in zip(agree.CLASSES, matrix, strict=True):
            lines.append(f"| {name} | " + " | ".join(str(value) for value in row) + " |")
        lines += [
            "",
            "A kappa that moves a lot between cuts is a statement about the cut, not "
            "the formula (§10 Phase 12's bucketing-choice sensitivity).",
        ]

    # ── RQ3 ──
    lines += [
        "",
        "## RQ3 — Do classifications survive perturbation?",
        "",
        "One parameter at a time; a flip is a change of class against the same "
        "vector unperturbed. Weight changes are renormalised so the four weights still "
        "sum to 1. File C H3: under 15% flips at ±20%; any parameter over 20% gets its "
        "own paragraph.",
        "",
    ]
    for label, summary in run.summaries.items():
        lines.append(
            f"- **{label}**: max weight-perturbation flip rate "
            f"{summary.max_weight_rate_10:.1%} at ±10%, {summary.max_weight_rate_20:.1%} "
            f"at ±20% ({'robust' if summary.robust else 'NOT robust'} by H3); max over every "
            f"parameter {summary.max_rate_overall:.1%}."
            + (
                f" Over 20%: {', '.join(summary.to_discuss)}."
                if summary.to_discuss
                else ""
            )
        )
    lines += [
        "",
        "| Vector | Parameter | Change | Flips | Rate | npm | pypi | mixed |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for label, rows in run.sensitivity.items():
        for row in rows:
            groups = {
                name: f"{flips}/{total}"
                for name, (flips, total) in row.by_ecosystem.items()
            }
            lines.append(
                f"| {label} | {row.parameter} | {row.change} | {row.flips}/{row.repositories} | "
                f"{row.rate:.1%} | {groups.get('npm', '-')} | {groups.get('pypi', '-')} | "
                f"{groups.get('mixed', '-')} |"
            )

    # ── RQ4 ──
    lines += ["", "## RQ4 — Do the known-bad anchors classify as at least Medium?", ""]
    if not run.anchor_rows:
        lines.append("No anchor set was given (`--anchors`), so RQ4 was not run.")
    else:
        lines += [
            f"Scanned {run.anchor_scan.get('scanned_at', '?')[:19]}Z, current state, through "
            "the corpus pipeline; nothing registered. A known anchor passes only if its "
            "repository is ≥ Medium **and** the scan saw the anchor package at the named "
            "version, flagged.",
            "",
            "| Repository | Bucket | Known anchor | Seen at version | Flags | "
            f"{run.baseline.version} | {CANDIDATE} | Verdict |",
            "|---|---|---|---|---|---|---|---|",
        ]
        baseline_by_url = {
            r.row.repo_url: r for r in run.anchor_results[run.baseline.version]
        }
        for result in run.anchor_results[CANDIDATE]:
            base = baseline_by_url[result.row.repo_url]
            seen = (
                ""
                if not result.row.is_known_anchor
                else (
                    f"yes ({result.anchor_occurrence.get('resolution')})"
                    if result.anchor_occurrence
                    else "**no**"
                )
            )
            lines.append(
                f"| `{result.row.full_name}` | {result.row.bucket} | "
                f"{result.row.anchor_package + '@' + (result.row.anchor_version or '') if result.row.is_known_anchor else ''} | "
                f"{seen} | {', '.join(result.anchor_flags)} | "
                f"{_score(base)} | {_score(result)} | "
                f"{result.verdict or ('scan: ' + str(result.scan.get('status')) if not result.scanned else '')} |"
            )
        outliers = [r for r in run.anchor_results[CANDIDATE] if r.bucket_outlier]
        lines += [
            "",
            "**Outliers** (seeded healthy but High-Alert, or seeded risky but Safe):",
            "",
        ]
        if outliers:
            for result in outliers:
                top = ", ".join(
                    f"{name} {points}" for name, points in result.top_contributors
                )
                lines.append(
                    f"- `{result.row.full_name}`: seeded {result.row.bucket}, scored "
                    f"{result.score} ({result.classification}). Largest penalties: {top or 'none'}."
                )
        else:
            lines.append("- none.")
        lines += ["", "**WP-2 quality checks**, against the scan:", ""]
        for check in run.anchor_checks:
            lines.append(
                f"- {'ok' if check.ok else '**check**'} — {check.check}: {check.value}"
            )

    # ── RQ5 ──
    lines += [
        "",
        "## RQ5 — Does the PyPI vector behave sanely on PyPI data?",
        "",
        "File C §2.4.6's trust gate for S3: the PyPI score distribution should use the "
        "range and populate the classes. Unweighted; the stale strata are oversampled "
        "(D14), so this shape is the corpus's, not GitHub's.",
        "",
        "| Formula | Group | Scores | Safe / Medium / High-alert | Median dependencies |",
        "|---|---|---|---|---|",
    ]
    for scored in run.vectors:
        for group in ("npm", "pypi", "mixed"):
            subset = [s for s in scored.scores if s.repository.ecosystem == group]
            if not subset:
                continue
            counts = [
                sum(s.classification == name for s in subset)
                for name in ("safe", "medium", "high_alert")
            ]
            deps = statistics.median(len(s.repository.occurrences) for s in subset)
            lines.append(
                f"| {scored.label} | {group} | {_distribution([float(s.score) for s in subset])} | "
                f"{' / '.join(str(c) for c in counts)} | {deps:g} |"
            )
    lines += [
        "",
        "§11.27: §5.3's roll-up gives a repository with more dependencies more chances "
        "at a worst case, so an ecosystem difference here is confounded with dependency "
        "count until S1 controls for it.",
    ]

    # ── limits, files ──
    lines += [
        "",
        "## What this report cannot show",
        "",
        "- **No temporal claim** (File C L12): one as-of snapshot per repository.",
        "- **No exploitation ground truth** (L3): nothing here says a dependency was attacked.",
        "- **Scorecard is a different construct** (L2) and **the OSV roll-up is circular** (L1).",
        "- **PyPI's vector is reasoned, not independently calibrated** (L4).",
        "- **GitHub, JS/TS + Python, manifests only** (L9, L10): no transitive "
        "dependencies, no call sites.",
        "",
        "## Files",
        "",
    ]
    for path in figures:
        lines.append(f"- `{path.name}`")
    if skipped_figures:
        lines.append(f"- Figures not drawn: {skipped_figures}")
    lines += [
        f"- `{CANDIDATE_FILENAME}` — the candidate `v2`, **not active**; adopt only after WP-6 signs.",
        "- `weights_comparison.csv`, `entropy.csv`, `scores.csv`, `correlation.csv`, "
        "`confusion.csv`, `sensitivity.csv`, "
        + ("`anchors.csv`, " if run.anchor_rows else "")
        + "`inputs.json`",
        "",
    ]
    return "\n".join(lines)


def _reference_name(key: str) -> str:
    return "Scorecard (independent)" if key == SCORECARD else "OSV roll-up (circular)"


def _score(result: anchors.AnchorResult) -> str:
    if result.score is None:
        return "-"
    return f"{result.score} ({result.classification})"


# ── CSVs ───────────────────────────────────────────────────────────────────


def _write_csv(path: Path, header: list[str], rows: list[list]) -> Path:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)
    return path


def write_csvs(run: ValidationRun, out: Path) -> list[Path]:
    written: list[Path] = []
    vectors = {
        run.baseline.version: run.baseline,
        CANDIDATE: run.candidate,
        ENTROPY: run.entropy_weights,
    }
    written.append(
        _write_csv(
            out / "weights_comparison.csv",
            ["formula", "ecosystem", *SIGNAL_NAMES],
            [
                [
                    label,
                    ecosystem,
                    *(str(weights.weights[ecosystem][s]) for s in SIGNAL_NAMES),
                ]
                for label, weights in vectors.items()
                for ecosystem in ("npm", "pypi")
            ]
            + [
                [
                    "ahp_eigenvector",
                    "",
                    *(f"{run.ahp.weight_vector()[s]:.6f}" for s in SIGNAL_NAMES),
                ]
            ],
        )
    )
    written.append(
        _write_csv(
            out / "entropy.csv",
            [
                "ecosystem",
                "sampling_weighted",
                "signal",
                "rows",
                "nonzero",
                "entropy",
                "weight",
                "ci_low",
                "ci_high",
            ],
            [
                [
                    ecosystem,
                    found.sampling_weighted,
                    column.signal,
                    column.rows,
                    column.nonzero,
                    column.entropy,
                    column.weight,
                    *(found.intervals.get(column.signal) or ("", "")),
                ]
                for results in (run.entropy, run.entropy_weighted)
                for ecosystem, found in results.items()
                for column in found.columns
            ],
        )
    )
    by_label = {
        scored.label: {s.repository.full_name: s for s in scored.scores}
        for scored in run.vectors
    }
    rows = []
    for repository in run.panel.repositories:
        name = repository.full_name
        reading = run.scorecards.get(name) if run.scorecards else None
        row = [
            name,
            repository.ecosystem,
            repository.sampling_weight if repository.sampling_weight is not None else "",
            len(repository.occurrences),
            repository.stored_score,
            repository.stored_version,
        ]
        for scored in run.vectors:
            result = by_label[scored.label][name]
            row += [result.score, result.classification]
        row += [
            reading.score if reading and reading.score is not None else "",
            reading.status if reading else "not_asked",
            f"{run.osv_health[name]:.1f}",
        ]
        rows.append(row)
    header = [
        "repository",
        "ecosystem",
        "sampling_weight",
        "occurrences",
        "stored_score",
        "stored_version",
    ]
    for scored in run.vectors:
        header += [f"score_{scored.label}", f"class_{scored.label}"]
    header += ["scorecard", "scorecard_status", "osv_health"]
    written.append(_write_csv(out / "scores.csv", header, rows))

    written.append(
        _write_csv(
            out / "correlation.csv",
            [
                "formula",
                "reference",
                "group",
                "covered",
                "repositories",
                "method",
                "weighted",
                "value",
                "ci_low",
                "ci_high",
            ],
            [
                [
                    found.vector,
                    found.reference,
                    found.group,
                    found.covered,
                    found.repositories,
                    correlation.method,
                    correlation.weighted,
                    correlation.value,
                    *(correlation.interval or ("", "")),
                ]
                for found in run.agreements
                for correlation in found.correlations
            ],
        )
    )
    written.append(
        _write_csv(
            out / "confusion.csv",
            [
                "formula",
                "reference",
                "group",
                "bucketing",
                "cuts",
                "kappa",
                "formula_class",
                "reference_bucket",
                "count",
            ],
            [
                [
                    found.vector,
                    found.reference,
                    found.group,
                    confusion.bucketing,
                    " ".join(f"{cut:.4f}" for cut in confusion.cuts),
                    confusion.kappa,
                    agree.CLASSES[i],
                    agree.CLASSES[j],
                    confusion.matrix[i][j],
                ]
                for found in run.agreements
                for confusion in found.confusions
                for i in range(len(agree.CLASSES))
                for j in range(len(agree.CLASSES))
            ],
        )
    )
    written.append(
        _write_csv(
            out / "sensitivity.csv",
            [
                "formula",
                "parameter",
                "change",
                "flips",
                "repositories",
                "rate",
                "by_ecosystem",
            ],
            [
                [
                    row.vector,
                    row.parameter,
                    row.change,
                    row.flips,
                    row.repositories,
                    f"{row.rate:.6f}",
                    json.dumps(row.by_ecosystem, sort_keys=True),
                ]
                for rows_ in run.sensitivity.values()
                for row in rows_
            ],
        )
    )
    if run.anchor_rows:
        base = {r.row.repo_url: r for r in run.anchor_results[run.baseline.version]}
        written.append(
            _write_csv(
                out / "anchors.csv",
                [
                    "repo_url",
                    "bucket_seeded",
                    "is_known_anchor",
                    "anchor_package",
                    "scan_status",
                    "anchor_seen",
                    "anchor_resolution",
                    "anchor_flags",
                    "observed_occurrences",
                    f"score_{run.baseline.version}",
                    f"class_{run.baseline.version}",
                    f"score_{CANDIDATE}",
                    f"class_{CANDIDATE}",
                    "verdict",
                    "bucket_outlier",
                ],
                [
                    [
                        r.row.repo_url,
                        r.row.bucket,
                        r.row.is_known_anchor,
                        f"{r.row.anchor_package}@{r.row.anchor_version}"
                        if r.row.anchor_package
                        else "",
                        r.scan.get("status"),
                        bool(r.anchor_occurrence),
                        (r.anchor_occurrence or {}).get("resolution", ""),
                        " ".join(r.anchor_flags),
                        r.observed_dependencies,
                        base[r.row.repo_url].score
                        if base[r.row.repo_url].score is not None
                        else "",
                        base[r.row.repo_url].classification or "",
                        r.score if r.score is not None else "",
                        r.classification or "",
                        r.verdict or "",
                        r.bucket_outlier,
                    ]
                    for r in run.anchor_results[CANDIDATE]
                ],
            )
        )
    return written


# ── figures ────────────────────────────────────────────────────────────────


def render_figures(run: ValidationRun, out: Path) -> list[Path]:
    """The three PNGs §10 Phase 12 names. Raises ImportError without matplotlib."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    written: list[Path] = []
    candidate = run.vector(CANDIDATE)
    if run.scorecards:
        figure, axis = plt.subplots(figsize=(7, 5))
        for ecosystem, marker in (("npm", "o"), ("pypi", "s"), ("mixed", "^")):
            points = [
                (run.scorecards[s.repository.full_name].score, float(s.score))
                for s in candidate.scores
                if s.repository.ecosystem == ecosystem
                and s.repository.full_name in run.scorecards
                and run.scorecards[s.repository.full_name].score is not None
            ]
            if points:
                axis.scatter(
                    *zip(*points, strict=True),
                    label=ecosystem,
                    marker=marker,
                    alpha=0.6,
                    s=18,
                )
        axis.set_xlabel("OpenSSF Scorecard (deps.dev), 0-10")
        axis.set_ylabel(f"Repository score under {CANDIDATE}")
        axis.set_xlim(0, 10)
        axis.set_ylim(0, 100)
        axis.legend()
        axis.set_title(f"Score vs Scorecard, corpus as of {run.panel.snapshot_date}")
        figure.tight_layout()
        path = out / "correlation_scatter.png"
        figure.savefig(path, dpi=150)
        plt.close(figure)
        written.append(path)

    figure, axes = plt.subplots(1, 2, figsize=(11, 4.5), sharey=True)
    for axis, ecosystem in zip(axes, ("npm", "pypi"), strict=True):
        series = [
            (run.baseline.version, run.baseline.weights[ecosystem]),
            (CANDIDATE, run.candidate.weights[ecosystem]),
            (ENTROPY, run.entropy_weights.weights[ecosystem]),
        ]
        width = 0.8 / len(series)
        for offset, (label, vector) in enumerate(series):
            axis.bar(
                [index + offset * width for index in range(len(SIGNAL_NAMES))],
                [float(vector[signal]) for signal in SIGNAL_NAMES],
                width=width,
                label=label,
            )
        axis.set_xticks([index + width for index in range(len(SIGNAL_NAMES))])
        axis.set_xticklabels(SIGNAL_NAMES)
        axis.set_title(ecosystem)
        axis.set_ylabel("weight")
    axes[0].legend()
    figure.suptitle("Weight vectors: active vs AHP candidate vs entropy")
    figure.tight_layout()
    path = out / "weight_comparison.png"
    figure.savefig(path, dpi=150)
    plt.close(figure)
    written.append(path)

    panels = [
        found
        for found in run.agreements
        if found.vector == CANDIDATE
        and found.group == "all"
        and found.confusion(agree.TERTILES)
    ]
    if panels:
        figure, axes = plt.subplots(
            1, len(panels), figsize=(5 * len(panels), 4.5), squeeze=False
        )
        for axis, found in zip(axes[0], panels, strict=True):
            matrix = found.confusion(agree.TERTILES).matrix
            axis.imshow(matrix, cmap="Blues")
            for i in range(3):
                for j in range(3):
                    axis.text(j, i, str(matrix[i][j]), ha="center", va="center")
            axis.set_xticks(range(3))
            axis.set_yticks(range(3))
            axis.set_xticklabels(agree.CLASSES)
            axis.set_yticklabels(agree.CLASSES)
            axis.set_xlabel(f"{found.reference} (tertiles)")
            axis.set_ylabel("formula class")
            kappa = found.confusion(agree.TERTILES).kappa
            axis.set_title(f"kappa = {_f(kappa)}")
        figure.tight_layout()
        path = out / "confusion_matrices.png"
        figure.savefig(path, dpi=150)
        plt.close(figure)
        written.append(path)
    return written


# ── everything ─────────────────────────────────────────────────────────────


def write_report(run: ValidationRun) -> list[Path]:
    """The folder, in full. Returns every file written."""
    out = run.inputs.out_dir
    out.mkdir(parents=True, exist_ok=True)
    written = write_csvs(run, out)

    figures: list[Path] = []
    skipped: str | None = None
    try:
        figures = render_figures(run, out)
    except ImportError as exc:
        # §11.22: "not installed" and "installed but blocked" both arrive here,
        # and the platform's own text is the only honest description of which.
        skipped = f"matplotlib could not be imported ({exc}); every figure's data is in the CSVs."

    candidate_text = candidates.render_weights_file(
        run.candidate,
        [
            "weights_v2 CANDIDATE - NOT ACTIVE. Written by validate_formula (§10 Phase 12).",
            "",
            f"npm vector: principal eigenvector of {run.ahp.matrix.source}",
            f"  (sha256 {run.ahp_sha256}), CR {run.ahp.consistency_ratio:.4f}.",
            *textwrap.wrap(run.pypi_rule, 76),
            f"Corpus snapshot {run.panel.snapshot_date}; report generated {run.generated_at[:19]}Z.",
            "",
            "Adopt only after WP-6 signs off: copy to backend/weights/weights_v2.yaml and",
            "set derivation to ahp-entropy-validated in that commit (§10 Phase 12, commit 7).",
        ],
    )
    candidate_path = out / CANDIDATE_FILENAME
    candidate_path.write_text(candidate_text, encoding="utf-8")
    written.append(candidate_path)

    inputs = {
        "generated_at": run.generated_at,
        "snapshot_date": run.panel.snapshot_date.isoformat(),
        "repositories": len(run.panel.repositories),
        "occurrences": run.panel.occurrence_count,
        "ahp_matrix": run.ahp.matrix.source,
        "ahp_matrix_sha256": run.ahp_sha256,
        "ahp": run.ahp.as_dict(),
        "anchor_set": run.inputs.anchors_path.name if run.inputs.anchors_path else None,
        "anchor_set_sha256": run.anchor_sha256,
        "baseline_weights": run.baseline.version,
        "pypi_rule": run.pypi_rule,
        "pypi_shift": run.inputs.pypi_shift,
        "seed": run.inputs.seed,
        "bootstrap": run.inputs.bootstrap,
        "reference_asked": not run.inputs.skip_reference,
        "reproduction": {
            "checked": run.reproduction.checked,
            "matched": run.reproduction.matched,
            "unloadable_versions": list(run.reproduction.unloadable_versions),
        },
        "checklist": [
            {"item": check.number, "title": check.title, "status": check.status}
            for check in checklist(run)
        ],
    }
    inputs_path = out / INPUTS_FILENAME
    inputs_path.write_text(
        json.dumps(inputs, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    written.append(inputs_path)

    report_path = out / REPORT_FILENAME
    report_path.write_text(render_markdown(run, figures, skipped), encoding="utf-8")
    written.append(report_path)
    written.extend(figures)
    run.files = written
    return written
