# Generated by Django 5.2.17 on 2026-08-30 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestFile',
            fields=[
                ('manifest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ecosystem', models.TextField(choices=[('npm', 'npm'), ('pypi', 'PyPI')])),
                ('manifest_path', models.TextField()),
                ('lockfile_path', models.TextField(blank=True, null=True)),
                ('parser_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'manifest_files',
                'ordering': ['manifest_path'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ecosystem', models.TextField(choices=[('npm', 'npm'), ('pypi', 'PyPI')])),
                ('package_name', models.TextField()),
                ('registry_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['ecosystem', 'package_name'],
                'constraints': [models.UniqueConstraint(fields=('ecosystem', 'package_name'), name='packages_unique_ecosystem_name'), models.CheckConstraint(condition=models.Q(('ecosystem__in', ['npm', 'pypi'])), name='packages_ecosystem_valid')],
            },
        ),
        migrations.CreateModel(
            name='DependencyOccurrence',
            fields=[
                ('dependency_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_group', models.TextField(choices=[('runtime', 'Runtime'), ('development', 'Development'), ('optional', 'Optional'), ('peer', 'Peer'), ('build', 'Build'), ('unknown', 'Unknown')], default='runtime')),
                ('declared_specifier', models.TextField()),
                ('resolved_version', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, choices=[('lockfile', 'From lockfile'), ('pinned', 'Pinned in manifest'), ('range_latest_approx', 'Approximated against latest')], null=True)),
                ('latest_version', models.TextField(blank=True, null=True)),
                ('latest_release_at', models.DateTimeField(blank=True, null=True)),
                ('staleness_days', models.IntegerField(blank=True, null=True)),
                ('versions_behind_major', models.IntegerField(default=0)),
                ('versions_behind_minor', models.IntegerField(default=0)),
                ('versions_behind_patch', models.IntegerField(default=0)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('deprecation_reason', models.TextField(blank=True, null=True)),
                ('is_unassessable', models.BooleanField(default=False)),
                ('unassessable_reason', models.TextField(blank=True, null=True)),
                ('vulnerability_count', models.IntegerField(default=0)),
                ('highest_severity', models.TextField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], null=True)),
                ('cvss_max', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cvss_reduced_confidence', models.BooleanField(default=False)),
                ('risk_component_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='scanning.manifestfile')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='occurrences', to='scanning.package')),
            ],
            options={
                'db_table': 'dependency_occurrences',
                'ordering': ['manifest__manifest_path', 'package__package_name'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.TextField(choices=[('initial', 'Initial'), ('manual', 'Manual')])),
                ('status', models.TextField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classification', models.TextField(blank=True, choices=[('safe', 'Safe'), ('medium', 'Medium'), ('high_alert', 'High alert')], null=True)),
                ('scoring_formula_version', models.TextField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='repositories.repository')),
                ('triggered_by', models.ForeignKey(db_column='triggered_by_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='triggered_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='manifestfile',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='scanning.scanrun'),
        ),
        migrations.CreateModel(
            name='DependencyVulnerability',
            fields=[
                ('vulnerability_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('osv_id', models.TextField()),
                ('cve_id', models.TextField(blank=True, null=True)),
                ('severity', models.TextField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], null=True)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('affected_range', models.TextField(blank=True, null=True)),
                ('fixed_version', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('epss_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanning.dependencyoccurrence')),
            ],
            options={
                'db_table': 'dependency_vulnerabilities',
                'ordering': ['osv_id'],
                'constraints': [models.UniqueConstraint(fields=('dependency', 'osv_id'), name='dep_vuln_unique_dependency_osv_id'), models.CheckConstraint(condition=models.Q(('severity__isnull', True), ('severity__in', ['low', 'medium', 'high', 'critical', 'unknown']), _connector='OR'), name='dep_vuln_severity_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='dependencyoccurrence',
            index=models.Index(fields=['manifest'], name='dep_occ_manifest_idx'),
        ),
        migrations.AddIndex(
            model_name='dependencyoccurrence',
            index=models.Index(fields=['is_flagged'], name='dep_occ_flagged_idx'),
        ),
        migrations.AddConstraint(
            model_name='dependencyoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('dependency_group__in', ['runtime', 'development', 'optional', 'peer', 'build', 'unknown'])), name='dep_occ_group_valid'),
        ),
        migrations.AddConstraint(
            model_name='dependencyoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__isnull', True), ('resolution__in', ['lockfile', 'pinned', 'range_latest_approx']), _connector='OR'), name='dep_occ_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='dependencyoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('highest_severity__isnull', True), ('highest_severity__in', ['low', 'medium', 'high', 'critical', 'unknown']), _connector='OR'), name='dep_occ_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='dependencyoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('vulnerability_count__gte', 0)), name='dep_occ_vuln_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='dependencyoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('versions_behind_major__gte', 0), ('versions_behind_minor__gte', 0), ('versions_behind_patch__gte', 0)), name='dep_occ_versions_behind_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='dependencyoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('risk_component_score__isnull', True), models.Q(('risk_component_score__gte', 0), ('risk_component_score__lte', 100)), _connector='OR'), name='dep_occ_component_score_range'),
        ),
        migrations.AddIndex(
            model_name='scanrun',
            index=models.Index(fields=['repository', '-created_at'], name='scan_runs_repo_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.CheckConstraint(condition=models.Q(('trigger_type__in', ['initial', 'manual'])), name='scan_runs_trigger_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'completed', 'failed'])), name='scan_runs_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__isnull', True), models.Q(('risk_score__gte', 0), ('risk_score__lte', 100)), _connector='OR'), name='scan_runs_risk_score_range'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.CheckConstraint(condition=models.Q(('classification__isnull', True), ('classification__in', ['safe', 'medium', 'high_alert']), _connector='OR'), name='scan_runs_classification_valid'),
        ),
        migrations.AddConstraint(
            model_name='manifestfile',
            constraint=models.UniqueConstraint(fields=('scan', 'manifest_path'), name='manifest_files_unique_scan_path'),
        ),
        migrations.AddConstraint(
            model_name='manifestfile',
            constraint=models.CheckConstraint(condition=models.Q(('ecosystem__in', ['npm', 'pypi'])), name='manifest_files_ecosystem_valid'),
        ),
    ]
