# Generated by Django 5.2.17 on 2026-09-01 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
        ('scanning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='skipped_manifest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.CheckConstraint(condition=models.Q(('skipped_manifest_count__gte', 0)), name='scan_runs_skipped_manifests_non_negative'),
        ),
    ]
