# Generated by Django 5.2.17 on 2026-09-09 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanning', '0002_scanrun_skipped_manifest_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.TextField(choices=[('combined', 'Combined'), ('per_dependency', 'Per dependency')])),
                ('status', models.TextField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued')),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('fixes_json', models.JSONField(blank=True, null=True)),
                ('citations_json', models.JSONField(blank=True, null=True)),
                ('retrieved_chunks_json', models.JSONField(blank=True, null=True)),
                ('grounding_confidence', models.TextField(blank=True, choices=[('sufficient', 'Sufficient'), ('low', 'Low')], null=True)),
                ('project_context_json', models.JSONField(blank=True, null=True)),
                ('model_name', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanning.dependencyoccurrence')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanning.scanrun')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scan', 'report_type'], name='reports_scan_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('report_type__in', ['combined', 'per_dependency'])), name='reports_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'completed', 'failed'])), name='reports_status_valid'), models.CheckConstraint(condition=models.Q(('grounding_confidence__isnull', True), ('grounding_confidence__in', ['sufficient', 'low']), _connector='OR'), name='reports_grounding_confidence_valid'), models.CheckConstraint(condition=models.Q(models.Q(('dependency__isnull', True), ('report_type', 'combined')), models.Q(('dependency__isnull', False), ('report_type', 'per_dependency')), _connector='OR'), name='reports_dependency_matches_type'), models.UniqueConstraint(condition=models.Q(('report_type', 'combined')), fields=('scan',), name='reports_one_combined_per_scan'), models.UniqueConstraint(condition=models.Q(('report_type', 'per_dependency')), fields=('scan', 'dependency'), name='reports_one_per_dependency_per_scan')],
            },
        ),
    ]
