"""The analysis notebooks' side of the replication package (§10 Phase 14).

`notebooks/13_3_validation.ipynb` (S1) and `notebooks/13_1_analysis.ipynb`
(S3) are thin: every computation they show is a function here, and every
function here is either the harness's own code fed from an export folder or a
comparison with what the harness wrote when the study's data was signed. That
is what "exports regenerate every notebook table" means in practice — the
tables are regenerated by the code that made them, from the files a stranger
has, and then checked against the signed copies.

**Nothing here opens a database.** The notebooks run under
`config.settings.offline`, whose database backend raises on the first query,
and these loaders read Parquet and JSON. The one network call either harness
could make (deps.dev for S1, the judge for S3) is replaced by its recorded
answers: WP-6's `depsdev_cache.jsonl` and WP-8's per-item verdicts in
`runs/analysis/metrics.csv`. A missing recorded answer fails rather than
fetching.

**What is recomputed and what is read.** S1: everything, from the stored
signals — scores, entropy weights, agreement, sensitivity, anchors — with
deps.dev's Scorecards read as observed on the day. S3: correctness, which is a
program, from the generations and the labelled set; faithfulness and
precision@k are the judge's verdicts as WP-8 recorded them (the judge cache is
withheld, decisions §13.17, and a judge call is not reproducible anyway).
"""

from __future__ import annotations

import csv
import difflib
import json
import math
import re
import shutil
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

from apps.research.experiment import analysis, judge, judge_validation, metrics, runner
from apps.research.export import DOCUMENTS, MANIFEST_FILENAME, sha256
from apps.research.validation import anchors, harness, panel, reference, report

#: Where `export_research_data` writes by default, relative to the repository.
DEFAULT_EXPORT = Path("research_data/exports")

VALIDATION_DIR = "validation_report"
RUNS_DIR = "runs"
ANALYSIS_DIR = "runs/analysis"
LABELLED_SET = "runs/ground_truth/labelled_set.jsonl"
SCORES_FILENAME = "scores.csv"

#: Lines of a regenerated file that carry the time it was generated and
#: nothing else, so a comparison with the signed copy skips them.
_GENERATED_MARKERS = (
    "Generated by `manage.py validate_formula`",
    '"generated_at"',
    "; report generated ",
)

#: How close two full-precision floats must be to count as the same number.
#: Python 3.12 made `sum()` of floats compensated (Neumaier), so a mean over
#: the same values can differ from 3.11's in its last bit or two; the signed
#: runs used 3.11 (decisions §14). Twelve significant digits is many orders
#: above that and many below anything a table prints.
FLOAT_TOLERANCE = 1e-12


class ReplicationError(Exception):
    """An export that cannot reproduce what the notebook asks of it."""


# ── the export, checked ────────────────────────────────────────────────────


@dataclass
class ExportCheck:
    directory: Path
    manifest: dict
    checked: int = 0
    mismatched: list[str] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.checked > 0 and not self.mismatched and not self.missing


def find_export(start: Path | None = None) -> Path:
    """The export folder: `$RV_EXPORTS`, else `research_data/exports` above `start`."""
    import os

    configured = os.environ.get("RV_EXPORTS")
    if configured:
        return Path(configured).expanduser().resolve()
    here = (start or Path.cwd()).resolve()
    for directory in (here, *here.parents):
        candidate = directory / DEFAULT_EXPORT
        if (candidate / MANIFEST_FILENAME).exists():
            return candidate
    raise ReplicationError(
        "No export found. Run `python manage.py export_research_data` from "
        "backend/ (REPLICATION.md §3), or set RV_EXPORTS to an export folder."
    )


def verify_export(directory: Path) -> ExportCheck:
    """Every file the manifest lists, checked against its sha256."""
    try:
        manifest = json.loads((directory / MANIFEST_FILENAME).read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ReplicationError(f"{directory} has no {MANIFEST_FILENAME}.") from exc
    check = ExportCheck(directory=directory, manifest=manifest)
    for entry in manifest["files"]:
        path = directory / entry["path"]
        if not path.exists():
            check.missing.append(entry["path"])
            continue
        check.checked += 1
        if sha256(path) != entry["sha256"]:
            check.mismatched.append(entry["path"])
    return check


def read_table(directory: Path, name: str) -> list[dict]:
    """One exported table's rows as dicts, decimals as `Decimal`."""
    import pyarrow.parquet as pq

    path = directory / f"{name}.parquet"
    if not path.exists():
        raise ReplicationError(f"{path} is missing; re-run export_research_data.")
    return pq.read_table(path).to_pylist()


# ── S1: the panel and the validation run ───────────────────────────────────


def validation_order(report_dir: Path) -> list[str]:
    """The repository order a signed validation run used, from its `scores.csv`.

    `load_panel` orders by the research database's collation (decisions §14),
    so this is the only record of the order WP-6's bootstrap resampled in.
    """
    with (report_dir / SCORES_FILENAME).open(encoding="utf-8", newline="") as handle:
        return [row["repository"] for row in csv.DictReader(handle)]


def panel_from_export(
    directory: Path,
    snapshot_date: date | None = None,
    *,
    order: list[str] | None = None,
) -> panel.CorpusPanel:
    """The corpus panel `load_panel` builds, from an export folder.

    Without `order`, repositories are sorted by name in code-point order, which
    is the same on every machine. With it, they follow `order` (a list of full
    names, as `validation_order` reads it); a repository it does not name is
    refused rather than appended, because a panel that silently differs from the
    one the order came from would reproduce nothing.
    """
    scans = [
        row
        for row in read_table(directory, "scan_history")
        if row["data_source"] == "corpus_scan"
    ]
    snapshots = sorted({row["snapshot_date"] for row in scans if row["snapshot_date"]})
    if snapshot_date is None:
        if len(snapshots) != 1:
            listed = ", ".join(day.isoformat() for day in snapshots) or "none"
            raise ReplicationError(
                f"Choose a snapshot: the export holds {listed}. A cross-section is "
                f"one snapshot (panel.resolve_snapshot)."
            )
        snapshot_date = snapshots[0]
    elif snapshot_date not in snapshots:
        raise ReplicationError(
            f"No corpus_scan rows as of {snapshot_date} in the export."
        )
    scans = [row for row in scans if row["snapshot_date"] == snapshot_date]

    if order is None:
        scans.sort(key=lambda row: (row["repo_full_name"], row["scan_history_id"]))
    else:
        position = {name: index for index, name in enumerate(order)}
        unknown = sorted(
            row["repo_full_name"]
            for row in scans
            if row["repo_full_name"] not in position
        )
        if unknown or len(scans) != len(order):
            raise ReplicationError(
                f"The order names {len(order)} repositories and the snapshot holds "
                f"{len(scans)}; not in the order: {', '.join(unknown[:5]) or 'none'}."
            )
        scans.sort(key=lambda row: position[row["repo_full_name"]])

    wanted = {row["scan_history_id"] for row in scans}
    occurrences = (
        tuple(row[column] for column in panel.OCCURRENCE_COLUMNS)
        for row in read_table(directory, "dependency_history")
        if row["scan_history_id"] in wanted
    )
    return panel.build_panel(
        snapshot_date,
        (tuple(row[column] for column in panel.SCAN_COLUMNS) for row in scans),
        occurrences,
    )


class _Recorded(reference.DepsDevClient):
    """deps.dev as WP-6 observed it: every answer must already be in the cache."""

    def project(self, full_name: str):  # pragma: no cover - reached only on a gap
        raise ReplicationError(
            f"deps.dev's answer for {full_name} is not in the recorded cache; "
            f"the replication reads what WP-6 saw and never asks again."
        )


def _no_client(**kwargs):  # pragma: no cover - reached only on a gap
    raise ReplicationError(
        "The anchor scan is not in the export; the replication reads WP-6's "
        "recorded scan and never scans GitHub."
    )


def rerun_validation(
    directory: Path, work_dir: Path, *, progress=None
) -> harness.ValidationRun:
    """WP-6's `validate_formula` run, again, from the export and offline.

    Its inputs are the ones the signed report recorded in `inputs.json` —
    matrix and anchor set (checked by sha256), snapshot, baseline version,
    PyPI rule, seed, bootstrap — and its panel is the export's, in the order
    the signed run used. Files are written to `work_dir`, never over the
    export.
    """
    signed = directory / VALIDATION_DIR
    recorded = json.loads((signed / report.INPUTS_FILENAME).read_text(encoding="utf-8"))
    ahp_path = directory / "ahp" / recorded["ahp_matrix"]
    anchors_path = (
        directory / "anchors" / recorded["anchor_set"] if recorded["anchor_set"] else None
    )
    for path, digest in (
        (ahp_path, recorded["ahp_matrix_sha256"]),
        (anchors_path, recorded["anchor_set_sha256"]),
    ):
        if path is not None and sha256(path) != digest:
            raise ReplicationError(
                f"{path.name} is not the file the signed report was computed from "
                f"(sha256 differs from inputs.json)."
            )

    if work_dir.exists():
        shutil.rmtree(work_dir)
    (work_dir / "anchors").mkdir(parents=True)
    if (signed / reference.CACHE_FILENAME).exists():
        shutil.copyfile(
            signed / reference.CACHE_FILENAME, work_dir / reference.CACHE_FILENAME
        )
    if (signed / anchors.SCAN_FILENAME).exists():
        shutil.copyfile(
            signed / anchors.SCAN_FILENAME, work_dir / "anchors" / anchors.SCAN_FILENAME
        )

    snapshot = date.fromisoformat(recorded["snapshot_date"])
    corpus = panel_from_export(directory, snapshot, order=validation_order(signed))
    inputs = harness.ValidationInputs(
        ahp_path=ahp_path,
        out_dir=work_dir,
        anchors_path=anchors_path,
        snapshot_date=snapshot,
        baseline_version=recorded["baseline_weights"],
        pypi_shift=recorded["pypi_shift"],
        seed=recorded["seed"],
        bootstrap=recorded["bootstrap"],
        skip_reference=not recorded["reference_asked"],
        rescan_anchors=False,
        wait_for_reset=False,
    )
    run = harness.run_validation(
        inputs,
        client_factory=_no_client,
        depsdev=_Recorded(),
        progress=progress,
        panel=corpus,
    )
    report.write_report(run)
    return run


# ── comparisons ────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class FileComparison:
    name: str
    identical: bool
    differences: tuple[str, ...] = ()
    #: Cells that are the same number to `FLOAT_TOLERANCE` but not the same
    #: text — a full-precision CSV regenerated on another Python's `sum()`.
    float_cells: int = 0

    @property
    def status(self) -> str:
        if not self.identical:
            return "differs"
        return "identical" if not self.float_cells else "equal to float precision"


def _comparable(text: str) -> list[str]:
    return [
        line
        for line in text.splitlines()
        if not any(marker in line for marker in _GENERATED_MARKERS)
    ]


def _same_number(first: str, second: str) -> bool:
    try:
        a, b = float(first), float(second)
    except ValueError:
        return False
    return math.isclose(a, b, rel_tol=FLOAT_TOLERANCE, abs_tol=FLOAT_TOLERANCE)


def _csv_cells(ours: list[str], theirs: list[str]) -> int | None:
    """Count float-only differences, or None if any cell differs in substance."""
    mine = list(csv.reader(ours))
    signed = list(csv.reader(theirs))
    if len(mine) != len(signed):
        return None
    loose = 0
    for row, other in zip(mine, signed, strict=True):
        if len(row) != len(other):
            return None
        for cell, signed_cell in zip(row, other, strict=True):
            if cell == signed_cell:
                continue
            if not _same_number(cell, signed_cell):
                return None
            loose += 1
    return loose


def compare_text(name: str, regenerated: str, signed: str) -> FileComparison:
    """Line by line, skipping only the lines that state when a file was generated.

    A CSV whose only differences are full-precision floats equal to
    `FLOAT_TOLERANCE` is reported as such rather than as different: every
    rounded table (`report.md`, `tables.md`) must still match exactly.
    """
    ours, theirs = _comparable(regenerated), _comparable(signed)
    if ours == theirs:
        return FileComparison(name, True)
    if name.endswith(".csv"):
        loose = _csv_cells(ours, theirs)
        if loose is not None:
            return FileComparison(name, True, float_cells=loose)
    diff = difflib.unified_diff(theirs, ours, "signed", "regenerated", lineterm="", n=0)
    return FileComparison(name, False, tuple(list(diff)[:40]))


def compare_folders(
    regenerated: Path, signed: Path, names: list[str]
) -> list[FileComparison]:
    results = []
    for name in names:
        if not (signed / name).exists():
            results.append(FileComparison(name, False, ("not in the signed folder",)))
            continue
        if not (regenerated / name).exists():
            results.append(FileComparison(name, False, ("not regenerated",)))
            continue
        results.append(
            compare_text(
                name,
                (regenerated / name).read_text(encoding="utf-8"),
                (signed / name).read_text(encoding="utf-8"),
            )
        )
    return results


#: The text files a validation run writes, all compared; the PNGs are drawn
#: from the same CSVs and are not compared byte for byte.
VALIDATION_FILES: tuple[str, ...] = (
    report.REPORT_FILENAME,
    report.INPUTS_FILENAME,
    report.CANDIDATE_FILENAME,
    "scores.csv",
    "entropy.csv",
    "weights_comparison.csv",
    "correlation.csv",
    "confusion.csv",
    "sensitivity.csv",
    "anchors.csv",
)


# ── S3: the runs and their tables ──────────────────────────────────────────


def run_directories(directory: Path) -> list[Path]:
    """Every run folder in the export, in condition order (A, B, C, D)."""
    found = []
    for path in sorted((directory / RUNS_DIR).iterdir()):
        manifest = path / runner.RUN_FILENAME
        if manifest.exists():
            condition = json.loads(manifest.read_text(encoding="utf-8"))["condition"]
            found.append((condition, path))
    return [path for _, path in sorted(found)]


def recorded_verdicts(directory: Path) -> dict[tuple[str, str], dict]:
    """The judge's verdicts per (item, condition), as WP-8's analysis wrote them."""
    path = directory / ANALYSIS_DIR / "metrics.csv"
    with path.open(encoding="utf-8", newline="") as handle:
        return {(row["item_id"], row["condition"]): row for row in csv.DictReader(handle)}


def _judgments(row: dict | None) -> dict:
    if row is None:
        return {}
    found: dict = {}
    if row["faithfulness"]:
        found[judge.FAITHFULNESS] = {
            "verdict": row["faithfulness"],
            "stated_verdict": row["stated_verdict"] or None,
        }
    if row["precision_at_k"]:
        found[judge.RELEVANCE] = {
            "precision_at_k": float(row["precision_at_k"]),
            "k": int(row["k"]),
        }
    return found


#: The columns of `metrics.csv` that are computed by program from the runs and
#: the labelled set — the ones a replication recomputes rather than reads.
DETERMINISTIC = (
    "ecosystem",
    "case_type",
    "answer_given",
    "status",
    "grounding",
    "branch",
    "correct",
    "correctness_reason",
    "declared_insufficient",
)


@dataclass
class S3Replication:
    dataset: analysis.Dataset
    #: (item, condition, column, recorded, recomputed) for every disagreement.
    disagreements: list[tuple[str, str, str, str, str]]


def _as_csv(value) -> str:
    return "" if value is None else str(value)


def s3_dataset(directory: Path) -> S3Replication:
    """WP-8's analysis dataset, with correctness recomputed from the generations."""
    items, _ = runner.load_items(directory / LABELLED_SET)
    by_id = {item["item_id"]: item for item in items}
    verdicts = recorded_verdicts(directory)
    run_dirs = run_directories(directory)
    if not run_dirs:
        raise ReplicationError(f"No run folders under {directory / RUNS_DIR}.")

    manifests = {}
    rows: list[metrics.ItemMetrics] = []
    disagreements = []
    unjudged = 0
    for run_dir in run_dirs:
        manifest = json.loads((run_dir / runner.RUN_FILENAME).read_text(encoding="utf-8"))
        manifests[manifest["condition"]] = manifest
        for record in runner.latest_records(run_dir / runner.ITEMS_FILENAME).values():
            item = by_id.get(record["item_id"])
            if item is None:
                raise ReplicationError(
                    f"{record['item_id']} is in {run_dir.name} but not in the labelled set."
                )
            recorded = verdicts.get((record["item_id"], record["condition"]))
            row = metrics.measure(record, item, _judgments(recorded))
            if row.status == "ok" and row.faithfulness is None:
                unjudged += 1
            rows.append(row)
            if recorded is None:
                disagreements.append(
                    (row.item_id, row.condition, "*", "", "not recorded")
                )
                continue
            for column in DETERMINISTIC:
                ours = _as_csv(getattr(row, column))
                if ours != recorded[column]:
                    disagreements.append(
                        (row.item_id, row.condition, column, recorded[column], ours)
                    )
    dataset = analysis.Dataset(runs=manifests, rows=rows, unjudged=unjudged)
    return S3Replication(dataset=dataset, disagreements=disagreements)


WP9_PACKET = "judge_validation/judge_validation_packet.md"
WP9_LABELS = "judge_validation/wp9_judge_labels.csv"


def wp9_candidates(directory: Path) -> list[judge_validation.Candidate]:
    """Every judged generation in the export, as the packet sampler saw them.

    The judge's verdict is the recorded one (`metrics.csv`); the passages are
    the ones the generation was shown, exactly as `judged_candidates` picks
    them, because the packet rendered those.
    """
    items, _ = runner.load_items(directory / LABELLED_SET)
    by_id = {item["item_id"]: item for item in items}
    verdicts = recorded_verdicts(directory)
    found: list[judge_validation.Candidate] = []
    for run_dir in run_directories(directory):
        for record in runner.latest_records(run_dir / runner.ITEMS_FILENAME).values():
            item = by_id.get(record["item_id"])
            recorded = verdicts.get((record["item_id"], record["condition"])) or {}
            if record.get("status") != "ok" or item is None:
                continue
            if not recorded.get("faithfulness"):
                continue
            shown_ids = set(record.get("shown_chunk_ids") or [])
            shown = [
                chunk
                for chunk in record.get("retrieved") or []
                if str(chunk.get("chunk_id")) in shown_ids
            ]
            found.append(
                judge_validation.Candidate(
                    run_dir.name,
                    record,
                    item,
                    {"verdict": recorded["faithfulness"], "shown": shown},
                )
            )
    return found


def wp9_key(directory: Path, *, seed: int = 42) -> dict[str, dict]:
    """WP-9's answer key, rebuilt from the export and checked against its packet.

    The sample size is the packet's own item count; the seed is the one every
    WP-9 packet was drawn with (REPLICATION.md §6).
    """
    packet = (directory / WP9_PACKET).read_text(encoding="utf-8")
    size = len(re.findall(r"^## ITEM-\d{3}$", packet, flags=re.MULTILINE))
    if not size:
        raise judge_validation.ValidationPacketError(
            f"{WP9_PACKET} holds no packet items."
        )
    return judge_validation.reconstruct_key(
        wp9_candidates(directory), packet, size=size, seed=seed
    )


def s3_tables(
    dataset: analysis.Dataset, work_dir: Path, *, bootstrap: int = 2000, seed: int = 42
) -> list[Path]:
    """`analyze_experiment`'s folder, rendered from `dataset` into `work_dir`."""
    if work_dir.exists():
        shutil.rmtree(work_dir)
    return analysis.write(dataset, work_dir, bootstrap=bootstrap, seed=seed)


def s3_table_files(directory: Path) -> list[str]:
    """The files WP-8's signed analysis folder holds, to compare one for one."""
    return sorted(
        path.name for path in (directory / ANALYSIS_DIR).iterdir() if path.is_file()
    )


def document_sources() -> dict[str, str]:
    """Export path -> deliverable path, for the notebooks' provenance table."""
    return {document.target: document.source for document in DOCUMENTS}


_PARAMETERS = re.compile(r"bootstrap over items, (\d+) resamples, seed (\d+)")


def analysis_parameters(directory: Path) -> tuple[int, int]:
    """The bootstrap size and seed the signed S3 tables state in their header."""
    text = (directory / ANALYSIS_DIR / "tables.md").read_text(encoding="utf-8")
    found = _PARAMETERS.search(text)
    if found is None:
        raise ReplicationError("The signed tables.md does not state its bootstrap.")
    return int(found.group(1)), int(found.group(2))


# ── what the notebooks show ────────────────────────────────────────────────


def manifest_summary(manifest: dict) -> str:
    """The export's receipt as a markdown table."""
    git = manifest.get("git") or {}
    commit = git.get("commit") or "unknown"
    dirty = " (local changes)" if git.get("dirty") else ""
    lines = [
        "| | |",
        "|---|---|",
        f"| Exported | {manifest['generated_at'][:19]}Z |",
        f"| At commit | `{commit[:12]}`{dirty} |",
        f"| Database | {manifest['database']['vendor']} `{manifest['database']['name']}` |",
        f"| Sources | {', '.join(manifest['sources'])} |",
    ]
    for name, table in manifest["tables"].items():
        detail = ", ".join(
            f"{key} {value}"
            for key, value in (table.get("by_snapshot_date") or {}).items()
        )
        lines.append(
            f"| `{name}` | {table['rows']} rows{f' ({detail})' if detail else ''} |"
        )
    lines.append(f"| Files | {len(manifest['files'])}, each with its sha256 |")
    return "\n".join(lines)


def comparison_table(results: list[FileComparison]) -> str:
    lines = ["| File | Against the signed copy |", "|---|---|"]
    for result in results:
        note = f" ({result.float_cells} cells)" if result.float_cells else ""
        lines.append(f"| `{result.name}` | **{result.status}**{note} |")
    return "\n".join(lines)


def classification_table(corpus: panel.CorpusPanel, versions: list[str]) -> str:
    """Safe / Medium / High alert per weights file, each recomputed (D6)."""
    from apps.scoring.weights import load_weights

    lines = [
        "| Weights | Derivation | Safe | Medium | High alert | Median score |",
        "|---|---|---|---|---|---|",
    ]
    for version in versions:
        weights = load_weights(version)
        scores = panel.score_panel(corpus, weights)
        counts = dict.fromkeys(("safe", "medium", "high_alert"), 0)
        for score in scores:
            counts[score.classification] += 1
        ordered = sorted(score.score for score in scores)
        middle = len(ordered) // 2
        median = (
            ordered[middle]
            if len(ordered) % 2
            else (ordered[middle - 1] + ordered[middle]) / 2
        )
        lines.append(
            f"| `{version}` | {weights.derivation} | {counts['safe']} | "
            f"{counts['medium']} | {counts['high_alert']} | {median:.2f} |"
        )
    return "\n".join(lines)


def reweighted(weights, multipliers: dict[str, float], *, version: str):
    """`weights` with signals multiplied and renormalized — a reviewer's "what if".

    File C §1.1: "a reviewer request like 'what if staleness were weighted
    double?' is a notebook cell, not a data-collection round."
    """
    from apps.research.validation import candidates

    vectors = {
        ecosystem: {
            signal: float(weight) * multipliers.get(signal, 1.0)
            for signal, weight in vector.items()
        }
        for ecosystem, vector in weights.weights.items()
    }
    return candidates.weightset_from(
        weights, vectors, version=version, derivation="notebook-reweighting"
    )


def flip_table(corpus: panel.CorpusPanel, before, after) -> str:
    """How many repositories change class between two weightings."""
    first = panel.score_panel(corpus, before)
    second = panel.score_panel(corpus, after)
    moves: dict[tuple[str, str], int] = {}
    for one, two in zip(first, second, strict=True):
        key = (one.classification, two.classification)
        moves[key] = moves.get(key, 0) + 1
    flipped = sum(count for (a, b), count in moves.items() if a != b)
    lines = [
        f"{flipped} of {len(first)} repositories change class "
        f"({flipped / len(first):.1%}) from `{before.version}` to `{after.version}`.",
        "",
        f"| `{before.version}` | `{after.version}` | Repositories |",
        "|---|---|---|",
    ]
    for (a, b), count in sorted(moves.items()):
        lines.append(f"| {a} | {b} | {count} |")
    return "\n".join(lines)
